name: Refresh site in Surge

on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Set up Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up dependencies
        run: yarn install
      - name: Build site
        run: yarn run build
        env:
          NODE_ENV: production
      - name: Publish site to Surge
        run: npx surge --project $GITHUB_WORKSPACE/dist --domain vlctechhub.org
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
      - name: Report published items
        run: yarn run report-published
        env:
          NODE_ENV: production
